// Code generated by mockery v2.25.0. DO NOT EDIT.

package mocks

import (
	entities "homework10/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: user
func (_m *UserRepository) AddUser(user entities.User) (int64, error) {
	ret := _m.Called(user)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.User) (int64, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(entities.User) int64); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(entities.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: id
func (_m *UserRepository) DeleteUser(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditUser provides a mock function with given fields: setUser
func (_m *UserRepository) EditUser(setUser entities.User) (*entities.User, error) {
	ret := _m.Called(setUser)

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.User) (*entities.User, error)); ok {
		return rf(setUser)
	}
	if rf, ok := ret.Get(0).(func(entities.User) *entities.User); ok {
		r0 = rf(setUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.User) error); ok {
		r1 = rf(setUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: id
func (_m *UserRepository) GetUserByID(id int64) (*entities.User, error) {
	ret := _m.Called(id)

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*entities.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *entities.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
